- name: Installing mariadb
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb
    - mariadb-server
    - python2-mysql

- name: Starting mariadb
  service:
    name: mariadb
    enabled: yes
    state: started

- name: Creating database
  mysql_db:
    name: "{{ wp_mysql_datb }}"
    state: present
    config_file: /etc/my.cnf

- name: Creating mysql user
  mysql_user:
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_pass }}"
    priv: "*.*:ALL"
